/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.portifolio;

/**
 *
 * @author victor.hrbarbosa
 */
public class Portifolio extends javax.swing.JFrame {

    /**
     * Creates new form Portifolio
     */
    public Portifolio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrograma1 = new javax.swing.JButton();
        btnPrograma2 = new javax.swing.JButton();
        btnPrograma3 = new javax.swing.JButton();
        btnPrograma4 = new javax.swing.JButton();
        btnPrograma6 = new javax.swing.JButton();
        btnprograma7 = new javax.swing.JButton();
        btnPrograma9 = new javax.swing.JButton();
        btnPrograma8 = new javax.swing.JButton();
        btnPrograma10 = new javax.swing.JButton();
        btnPrograma5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPrograma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/Calculator-icon2.png"))); // NOI18N
        btnPrograma1.setToolTipText("Quer saber se voce vai realmente passar de ano e nao vai ficar no pic e ser aprovado diretamente pelo sistema mesmo nao aprendendo nada esse programa e perfeito");
        btnPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma1ActionPerformed(evt);
            }
        });

        btnPrograma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/imc.png"))); // NOI18N
        btnPrograma2.setToolTipText("Voce que esta ai preocupado com seu peso nao quer saber se voce perdeu realmente aqueles kilos diferentes com a calculadora icm voce pode ver se deu aquela emagrecida ");
        btnPrograma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma2ActionPerformed(evt);
            }
        });

        btnPrograma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/tanque.png"))); // NOI18N
        btnPrograma3.setToolTipText("Voce que esta cansado de ser enganado pelo governo e esta afim de compra gasolina ou alcool esse programa diz se compensa compra alcool ou gasolina");
        btnPrograma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma3ActionPerformed(evt);
            }
        });

        btnPrograma4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_Board-Games-grey_190295.png"))); // NOI18N
        btnPrograma4.setToolTipText("Divirta-se e se distraia jogando aquel dadinho maroto e torcendo pelo seu numero da sorte de 1 a 6");
        btnPrograma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma4ActionPerformed(evt);
            }
        });

        btnPrograma6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_document_2318462 (1).png"))); // NOI18N
        btnPrograma6.setToolTipText("Voce vs a maquina quem ganha veja");
        btnPrograma6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma6ActionPerformed(evt);
            }
        });

        btnprograma7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_1_5_387520.png"))); // NOI18N
        btnprograma7.setToolTipText("Calculadora simples (Botao pode ser atualizado no futuro)");
        btnprograma7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprograma7ActionPerformed(evt);
            }
        });

        btnPrograma9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victor\\Documents\\NetBeansProjects\\Portifoliodefinitivo\\src\\br\\com\\senac\\icones\\if_Cardgame_3311.png")); // NOI18N
        btnPrograma9.setToolTipText("Sorteio de cartas");
        btnPrograma9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma9ActionPerformed(evt);
            }
        });

        btnPrograma8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_9_2388606.png"))); // NOI18N
        btnPrograma8.setToolTipText("Voce que nao gosta de estudar a tabuada em livros de matematica as veses vc foleia e so que a tabuada e fica procurando no meio de um monte de contas que voce provavelmente saiba fazer tente esse programa ira ajudalo");
        btnPrograma8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma8ActionPerformed(evt);
            }
        });

        btnPrograma10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_icon-play_211876.png"))); // NOI18N
        btnPrograma10.setToolTipText("Isso aqui e um app que criei e nao usei codigos que o professor pasou eu fui alem e li bastante coisa pra saber sobre o encapsulamento e acabei achando bacana criar um controle remoto e pensei em crialo bem simples");
        btnPrograma10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma10ActionPerformed(evt);
            }
        });

        btnPrograma5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if__Battle_1337441.png"))); // NOI18N
        btnPrograma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrograma9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(btnprograma7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrograma10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnPrograma2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnPrograma6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrograma5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPrograma4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrograma8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrograma3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrograma2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(btnPrograma10)
                        .addGap(36, 36, 36)
                        .addComponent(btnPrograma9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrograma3)
                            .addComponent(btnPrograma6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrograma4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnPrograma8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrograma5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnprograma7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        setBounds(0, 0, 655, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma1ActionPerformed
        // TODO add your handling code here:
        CalculoMedia programa1 = new CalculoMedia();
        programa1.setVisible(true);
    }//GEN-LAST:event_btnPrograma1ActionPerformed

    private void btnPrograma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma2ActionPerformed
        Icm programa2 = new Icm();
        programa2.setVisible(true);
    }//GEN-LAST:event_btnPrograma2ActionPerformed

    private void btnPrograma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma3ActionPerformed
        AlcoolxGasolina programa3 = new AlcoolxGasolina();
        programa3.setVisible(true);
    }//GEN-LAST:event_btnPrograma3ActionPerformed

    private void btnPrograma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma4ActionPerformed
        JogodoDado programa4 = new JogodoDado();
        programa4.setVisible(true);
    }//GEN-LAST:event_btnPrograma4ActionPerformed

    private void btnPrograma6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma6ActionPerformed
        // TODO add your handling code here:
        JokenPoApha programa6 = new JokenPoApha();
        programa6.setVisible(true);
        
        
    }//GEN-LAST:event_btnPrograma6ActionPerformed

    private void btnprograma7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprograma7ActionPerformed
        Calculadora programa7 = new Calculadora();
        programa7.setVisible(true);
    }//GEN-LAST:event_btnprograma7ActionPerformed

    private void btnPrograma8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma8ActionPerformed
        Tabuada programa8 = new Tabuada();
        programa8.setVisible(true);
    }//GEN-LAST:event_btnPrograma8ActionPerformed

    private void btnPrograma10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma10ActionPerformed
        // TODO add your handling code here:
        RemoteControler programa11 = new RemoteControler();
        programa11.setVisible(true);
        
       
    }//GEN-LAST:event_btnPrograma10ActionPerformed

    private void btnPrograma9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma9ActionPerformed
        Cartaz programa9 = new Cartaz();
        programa9.setVisible(true);
    }//GEN-LAST:event_btnPrograma9ActionPerformed

    private void btnPrograma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma5ActionPerformed
        // TODO add your handling code here:
        ParouImpar programa5 = new ParouImpar();
        programa5.setVisible(true);
    }//GEN-LAST:event_btnPrograma5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portifolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portifolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portifolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portifolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portifolio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrograma1;
    private javax.swing.JButton btnPrograma10;
    private javax.swing.JButton btnPrograma2;
    private javax.swing.JButton btnPrograma3;
    private javax.swing.JButton btnPrograma4;
    private javax.swing.JButton btnPrograma5;
    private javax.swing.JButton btnPrograma6;
    private javax.swing.JButton btnPrograma8;
    private javax.swing.JButton btnPrograma9;
    private javax.swing.JButton btnprograma7;
    // End of variables declaration//GEN-END:variables
}
