/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.portifolio;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/**
 *
 * @author victor.hrbarbosa
 */
public class RemoteControler extends javax.swing.JFrame {
    public int listavolume;
    public boolean play_pause;
    public boolean on_off;

    public boolean isPlay_pause() {
        return play_pause;
    }

    public void setPlay_pause(boolean playpause) {
        this.play_pause = playpause;
    }

    public boolean isOn_off() {
        return on_off;
    }

    public void setOn_off(boolean onoff) {
        this.on_off = onoff;
    }
    

    public int getListavolume() {
        return listavolume;
    }

    public void setListavolume(int listavolume) {
        this.listavolume = listavolume;
    }
     
    
    
    DefaultListModel lista = new DefaultListModel();
    
     public void maisvolume(){
       
       //volume1 = Integer.parseInt(btnmaisvolume.getActionCommand());
       
       listMenu.setModel(lista);
         if (this.isOn_off()) {
             this.setListavolume(this.getListavolume() + 1);
             lista.addElement("Volume: " + (this.getListavolume()));
         } else if (this.isOn_off() == false) {
             lblError.setText("nao foi possivel de aumentar volume");
         }
            
         if (this.getListavolume() >= 99) {
             this.setListavolume(99);
         } else {
         }
     }
     
     public void menosvolume(){
       
       //volume1 = Integer.parseInt(btnmaisvolume.getActionCommand());

       
      
       listMenu.setModel(lista);
       
       if (this.isOn_off()) {
             this.setListavolume(this.getListavolume() - 1);
             lista.addElement("Volume: " + (this.getListavolume()));
             
         } else if (this.isOn_off() == false) {
             
             lblError.setText("nao foi possivel diminuir  volume");
         } 
         if (this.getListavolume() <=1) {
             this.setListavolume(1);
         } else {
         }
         
               
     }
     
     public void ligar(){
        listMenu.setModel(lista);
        this.setListavolume(50);
        this.setOn_off(true);
        lblError.setText("ligando a tv");     }
     
     public void desligar(){
        this.setOn_off(false);
        lblError.setText("desligando a tv");
     }
     
     public void menu(){
         lista.clear();
         lista.addElement("Volume: " + (this.getListavolume()));
         lista.addElement("status da tv: " + (this.isOn_off()));
         lista.addElement("Ela esta tocando: " + (this.isPlay_pause()));
     }
     
     public void play(){
         if (this.isPlay_pause() == false && (this.isOn_off())) {
             this.setPlay_pause(true);
         } else {
             lblError.setText("ligue a tv primeiro");
         }
     }
     
     public void pause(){
         if (this.isPlay_pause() && (this.isOn_off())) {
             this.setPlay_pause(false);
         } else {
             
         }
     }

    /**
     * Creates new form RemoteControler
     */
    public RemoteControler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDesligar_ligar = new javax.swing.JButton();
        btnMaisvolume = new javax.swing.JButton();
        btnMenosvolume = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMenu = new javax.swing.JList<>();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDesligar_ligar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_flat-style-circle-turn-on-off_1312510.png"))); // NOI18N
        btnDesligar_ligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesligar_ligarActionPerformed(evt);
            }
        });

        btnMaisvolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_add-80px_510912.png"))); // NOI18N
        btnMaisvolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisvolumeActionPerformed(evt);
            }
        });

        btnMenosvolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_minus_1814110.png"))); // NOI18N
        btnMenosvolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosvolumeActionPerformed(evt);
            }
        });

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_menu6_216511.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_icon-play_211876.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/if_pause-circle-fill_326567.png"))); // NOI18N
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        listMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMenu);

        lblError.setText("error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDesligar_ligar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenosvolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaisvolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(302, 302, 302))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnMenu)
                .addGap(34, 34, 34)
                .addComponent(btnPlay)
                .addGap(31, 31, 31)
                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesligar_ligar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMaisvolume, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addComponent(btnMenosvolume, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPause, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblError)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaisvolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisvolumeActionPerformed
        // TODO add your handling code here:
        maisvolume();
    }//GEN-LAST:event_btnMaisvolumeActionPerformed

    private void btnMenosvolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosvolumeActionPerformed
        // TODO add your handling code here:
        menosvolume();
    }//GEN-LAST:event_btnMenosvolumeActionPerformed

    private void btnDesligar_ligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesligar_ligarActionPerformed
        // TODO add your handling code here:
        if (this.isOn_off() == false) {
            ligar();
        } else {
            desligar();
        }
    }//GEN-LAST:event_btnDesligar_ligarActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        play();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        pause();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        menu();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoteControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoteControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoteControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoteControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoteControler().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesligar_ligar;
    private javax.swing.JButton btnMaisvolume;
    private javax.swing.JButton btnMenosvolume;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    public javax.swing.JList<String> listMenu;
    // End of variables declaration//GEN-END:variables
}
